version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: db # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  dbdata:
